listenat: :8888
videoacc:
  redisaddress: localhost:6379
  redispassword: ""
  redishashsetname: acc_views
  redishashshufflesuffix: _inprogress
  mysqladdress: ""
  mysqlpassword: ""
  mysqldb: localhost:3306
  mysqltable: test.tshare
  mysqlfield: playtimes
  mysqlkey: "no"
  flushintervalsecond: 2
  maxkeycached: 1000
  writedbtimeout: 0
  failretrytimes: 0

