listenat: :8888
videoacc:
  redisaddress: localhost:6379
  redispassword: ""
  redishashsetname: acc_views
  redishashshufflesuffix: _inprogress
  mysqladdress: ""
  mysqlpassword: ""
  mysqldb: localhost:3306
  mysqltable: testdb.test
  mysqlfield: ""
  flushintervalsecond: 60
  maxkeycached: 10000
  writedbtimeout: 0
  failretrytimes: 0

